### ISSUE TITLE
faviconが存在するかチェックしているが現時点では無意味となっている

### ISSUE THREAD

**Issue by otofune** [syuilo/summaly#62]
[src/general.ts#L92-L94](https://github.com/syuilo/summaly/blob/2b01979fb26011d359dab5a54c4829c5a22c1033/src/general.ts#L92-L94) でfaviconの存在が確認できたときのみというようにしているように見える
だが [src/general.ts#L97](https://github.com/syuilo/summaly/blob/2b01979fb26011d359dab5a54c4829c5a22c1033/src/general.ts#L97) でnull時にチェックなしで `URL.resolve(url.href, '/favicon.ico')` を挿入してしまっている

**Comment by syuilo** [comment]
ん？

**Comment by syuilo** [comment]
`icon ? `って三項演算子使ってるからnullチェックしてることにならない？

**Comment by otofune** [comment]
いや、それはなるんだけど、
[src/general.ts#L77-L95](https://github.com/syuilo/summaly/blob/2b01979fb26011d359dab5a54c4829c5a22c1033/src/general.ts#L77-L95) で既に同じ `URL.resolve(url.href, favicon)` を**存在するかチェックしてから**挿入処理していて、挿入されていない (要するにファイルが実在しない) 時にもう1度3項演算子でnullチェックすることにより**存在しない**faviconのURLを挿入してしまうんです

**Comment by otofune** [comment]
すいません、コード読み違えてました・・・このIssueのバグは誤報告です・・・
favicon周りで問題があるのはそうなんですが、問題が有るのは`URL.resolve(url.href, '/favicon.ico')` でした
